//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_用户信息表
    {
        public int 编码 { get; set; }
        public string 姓名 { get; set; }
        public string 登录名 { get; set; }
        public string 密码 { get; set; }
        public string 权限 { get; set; }
        public Nullable<int> 类型 { get; set; }
        public string 工作组 { get; set; }
        public string AM_SERVER { get; set; }
    }
}
