//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMMS_生产设备编码表
    {
        public string 设备编码 { get; set; }
        public string 设备简称 { get; set; }
        public string 设备编号 { get; set; }
        public string 设备名称 { get; set; }
        public string 计量单位 { get; set; }
        public string 购入日期 { get; set; }
        public string 使用日期 { get; set; }
        public string 使用部门编码 { get; set; }
        public string 保管人 { get; set; }
        public string 存放地点 { get; set; }
        public string 生产厂家 { get; set; }
        public Nullable<decimal> 准备工时 { get; set; }
        public Nullable<decimal> 产能 { get; set; }
        public string 外形尺寸 { get; set; }
        public string 设备类别 { get; set; }
        public string 总功率 { get; set; }
        public string 照片编码 { get; set; }
        public string 设备状况 { get; set; }
        public string 备注 { get; set; }
        public string 机型类别 { get; set; }
        public string 型号 { get; set; }
        public string 最大尺寸 { get; set; }
        public string 最小尺寸 { get; set; }
        public string 纸张厚度 { get; set; }
        public string 重量 { get; set; }
        public string 最大工作压力 { get; set; }
        public string 最高工作速度 { get; set; }
    }
}
