//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MCMS_设计订单_Master
    {
        public string 订单号 { get; set; }
        public string 业务单号 { get; set; }
        public string 订单名称 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public string 联系方式 { get; set; }
        public Nullable<System.DateTime> 交稿日期 { get; set; }
        public Nullable<System.DateTime> 接稿日期 { get; set; }
        public Nullable<System.DateTime> 定稿日期 { get; set; }
        public Nullable<int> 开数编码 { get; set; }
        public string 合同编号 { get; set; }
        public string 客户类型 { get; set; }
        public string 装订方法 { get; set; }
        public string 客户单号 { get; set; }
        public string 送样数量 { get; set; }
        public Nullable<System.DateTime> 送样日期 { get; set; }
        public Nullable<int> 成品数量 { get; set; }
        public string 计量单位 { get; set; }
        public string 展开尺寸 { get; set; }
        public string 成品尺寸 { get; set; }
        public Nullable<int> 页数 { get; set; }
        public string 印品类别编码 { get; set; }
        public string 单据类型 { get; set; }
        public string 客户地址 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public string 特殊要求 { get; set; }
        public string 加工要求 { get; set; }
        public string 制单人编码 { get; set; }
        public System.DateTime 制单日期 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public string 印品方向 { get; set; }
        public Nullable<int> 内页P数 { get; set; }
        public Nullable<int> 封面P数 { get; set; }
        public Nullable<int> 总P数 { get; set; }
        public string 客户来源 { get; set; }
        public Nullable<System.DateTime> 初稿日期 { get; set; }
        public string 设计员编码 { get; set; }
        public string 策划员编码 { get; set; }
        public string 制作员编码 { get; set; }
        public string 版票 { get; set; }
        public string 信封 { get; set; }
        public string 戳 { get; set; }
        public string 纪念章 { get; set; }
        public string 照片 { get; set; }
        public string 光盘 { get; set; }
        public string 资料书 { get; set; }
        public string 彩喷稿 { get; set; }
        public string 其他 { get; set; }
        public string 备注 { get; set; }
    }
}
