//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MIMS_纸张编码表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_MIMS_纸张编码表()
        {
            this.T_MIMS_纸张期初库存表 = new HashSet<T_MIMS_纸张期初库存表>();
        }
    
        public string 纸张编码 { get; set; }
        public string 纸张名称 { get; set; }
        public string 规格 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<int> 重量 { get; set; }
        public string 产地 { get; set; }
        public string 类别 { get; set; }
        public Nullable<decimal> 宽 { get; set; }
        public Nullable<decimal> 高 { get; set; }
        public string 纸型 { get; set; }
        public Nullable<short> 是否启用批次 { get; set; }
        public Nullable<decimal> 安全库存下限 { get; set; }
        public Nullable<decimal> 安全库存上限 { get; set; }
        public string 备注 { get; set; }
        public Nullable<decimal> 计划单价 { get; set; }
        public Nullable<decimal> 采购单价 { get; set; }
        public Nullable<decimal> 销售单价 { get; set; }
        public Nullable<decimal> 单张面积 { get; set; }
        public Nullable<int> 禁用标识 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MIMS_纸张期初库存表> T_MIMS_纸张期初库存表 { get; set; }
    }
}
