//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MIMS_材料编码表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_MIMS_材料编码表()
        {
            this.T_MIMS_材料期初表 = new HashSet<T_MIMS_材料期初表>();
        }
    
        public string 材料类别编码 { get; set; }
        public string 仓库编码 { get; set; }
        public string 材料编码 { get; set; }
        public string 材料名称 { get; set; }
        public string 规格型号 { get; set; }
        public string 备注 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<decimal> 计划单价 { get; set; }
        public string 图片存储路径 { get; set; }
        public Nullable<decimal> 安全库存上限 { get; set; }
        public Nullable<decimal> 安全库存下限 { get; set; }
        public Nullable<int> 辅料标志 { get; set; }
        public Nullable<int> 主料标志 { get; set; }
        public string 废料编码 { get; set; }
        public string 废料名称 { get; set; }
        public Nullable<int> 废料标志 { get; set; }
        public Nullable<int> 禁用标识 { get; set; }
    
        public virtual T_MIMS_材料类别编码表 T_MIMS_材料类别编码表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MIMS_材料期初表> T_MIMS_材料期初表 { get; set; }
    }
}
