//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MIMS_材料类别编码表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_MIMS_材料类别编码表()
        {
            this.T_MIMS_材料编码表 = new HashSet<T_MIMS_材料编码表>();
        }
    
        public string 材料类别编码 { get; set; }
        public string 材料类别名称 { get; set; }
        public string 备注 { get; set; }
        public string 统计类别 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MIMS_材料编码表> T_MIMS_材料编码表 { get; set; }
    }
}
