//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_合同_Detail_印品
    {
        public int 行号 { get; set; }
        public string 合同号 { get; set; }
        public string 印品名称 { get; set; }
        public string 成品尺寸 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 品种 { get; set; }
        public Nullable<decimal> 成品数量 { get; set; }
        public Nullable<decimal> 合同金额 { get; set; }
        public Nullable<decimal> 不含税金额 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public string 备注 { get; set; }
    }
}
