//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_订单_发货申请单
    {
        public string 申请单号 { get; set; }
        public Nullable<System.DateTime> 日期 { get; set; }
        public string 订单号 { get; set; }
        public string 申请人编码 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public string 发货地址 { get; set; }
        public string 发货地址二 { get; set; }
        public string 发货地址三 { get; set; }
        public string 联系方式 { get; set; }
        public string 联系方式二 { get; set; }
        public string 联系方式三 { get; set; }
        public string 印品名称 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
        public Nullable<decimal> 发货数量 { get; set; }
        public string 备注 { get; set; }
        public string 制单人编码 { get; set; }
        public Nullable<System.DateTime> 制单日期 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public Nullable<int> 发货标识 { get; set; }
        public string 发货人编码 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public Nullable<int> 结款标识 { get; set; }
        public Nullable<System.DateTime> 标识日期 { get; set; }
    }
}
