//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_报价单_Master
    {
        public string 订单号 { get; set; }
        public string 业务单号 { get; set; }
        public string 产品编码 { get; set; }
        public string 订单名称 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public string 单据类型 { get; set; }
        public string 印品密级 { get; set; }
        public string 联系方式 { get; set; }
        public Nullable<int> 成品数量 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<int> 开数编码 { get; set; }
        public Nullable<int> 成品尺寸高 { get; set; }
        public Nullable<int> 成品尺寸长 { get; set; }
        public Nullable<int> 成品尺寸宽 { get; set; }
        public string 成品尺寸 { get; set; }
        public string 装订方法 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public string 报价要求 { get; set; }
        public string 制单人编码 { get; set; }
        public System.DateTime 制单日期 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public string 设计员编码 { get; set; }
        public string 制作员编码 { get; set; }
        public Nullable<decimal> 印张 { get; set; }
        public string 合同号 { get; set; }
        public string 送样数量 { get; set; }
        public string 印品类别编码 { get; set; }
        public string 书号 { get; set; }
        public Nullable<decimal> 定价 { get; set; }
        public string 版次 { get; set; }
        public Nullable<decimal> 总页数 { get; set; }
        public Nullable<int> 插页数 { get; set; }
        public string 拼版出血 { get; set; }
        public Nullable<int> 是否开票 { get; set; }
        public string 合同编号 { get; set; }
        public string 菲林状况 { get; set; }
        public string 样稿类型 { get; set; }
        public string 样稿随货带走 { get; set; }
        public string 生产单号 { get; set; }
        public Nullable<decimal> 包装费率 { get; set; }
        public Nullable<decimal> 开票税率 { get; set; }
        public Nullable<decimal> 运输费率 { get; set; }
        public Nullable<decimal> 仓贮费率 { get; set; }
        public Nullable<decimal> 纸张放率 { get; set; }
        public Nullable<int> 烫金面积 { get; set; }
        public Nullable<int> 烫金起步面积 { get; set; }
        public Nullable<int> UV面积 { get; set; }
        public Nullable<int> UV起步面积 { get; set; }
        public string 烫金尺寸 { get; set; }
        public string 烫金起步 { get; set; }
        public Nullable<decimal> 烫金起步单价 { get; set; }
        public string UV尺寸 { get; set; }
        public string UV起步 { get; set; }
        public Nullable<decimal> UV起步单价 { get; set; }
        public string 内部说明 { get; set; }
    }
}
