//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_报价单_Detail_材料
    {
        public int 行号 { get; set; }
        public string 订单号 { get; set; }
        public string 印品部件 { get; set; }
        public string 材料来源 { get; set; }
        public string 材料类别编码 { get; set; }
        public string 材料编码 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
        public string 项目编码 { get; set; }
        public Nullable<decimal> 仓库数量 { get; set; }
        public Nullable<decimal> 请购数量 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 备注 { get; set; }
        public string 变更单号 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<decimal> 单个单价 { get; set; }
        public Nullable<decimal> 匹配系数 { get; set; }
        public Nullable<int> 报价detail号 { get; set; }
    }
}
