//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_业务报价单_Master
    {
        public string 报价单号 { get; set; }
        public string 订单号 { get; set; }
        public string 订单名称 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public string 合同编号 { get; set; }
        public Nullable<decimal> 印张 { get; set; }
        public Nullable<int> 成品数量 { get; set; }
        public string 计量单位 { get; set; }
        public string 成品尺寸 { get; set; }
        public Nullable<int> 开数编码 { get; set; }
        public string 装订方法 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public System.DateTime 制单日期 { get; set; }
        public string 审核人编码 { get; set; }
    }
}
