//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_订单_Detail_工艺
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_OMS_订单_Detail_工艺()
        {
            this.T_OMS_订单_Detail_计价 = new HashSet<T_OMS_订单_Detail_计价>();
        }
    
        public int 行号 { get; set; }
        public string 订单号 { get; set; }
        public string 印品部件 { get; set; }
        public string 项目编码 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
        public string 变更单号 { get; set; }
        public Nullable<int> 排序码 { get; set; }
        public Nullable<int> 订单detail号 { get; set; }
    
        public virtual T_OMS_订单_Detail T_OMS_订单_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OMS_订单_Detail_计价> T_OMS_订单_Detail_计价 { get; set; }
    }
}
