//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_基础_加放率表
    {
        public int 序号 { get; set; }
        public string 纸型 { get; set; }
        public string 印品部件 { get; set; }
        public Nullable<int> 正面色数 { get; set; }
        public string 色数 { get; set; }
        public Nullable<int> 背面色数 { get; set; }
        public Nullable<int> 最低重量 { get; set; }
        public Nullable<int> 最高重量 { get; set; }
        public Nullable<int> 最低印数 { get; set; }
        public Nullable<int> 最高印数 { get; set; }
        public Nullable<decimal> 印刷业务放数 { get; set; }
        public Nullable<decimal> 装订业务放数 { get; set; }
        public Nullable<decimal> 印刷业务加放率 { get; set; }
        public Nullable<decimal> 装订业务加放率 { get; set; }
        public Nullable<decimal> 印刷生产放数 { get; set; }
        public Nullable<decimal> 装订生产放数 { get; set; }
        public Nullable<decimal> 印刷生产加放率 { get; set; }
        public Nullable<decimal> 装订生产加放率 { get; set; }
        public string 备注 { get; set; }
    }
}
