//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_客户编码表
    {
        public int 客户编码 { get; set; }
        public string 客户名称 { get; set; }
        public string 客户简称 { get; set; }
        public string 联系人 { get; set; }
        public string 电话 { get; set; }
        public string 传真 { get; set; }
        public string 客户类别 { get; set; }
        public string 业务员编码 { get; set; }
        public string 负责人电话 { get; set; }
        public string 客户级别 { get; set; }
        public string 送货要求 { get; set; }
        public string 账期说明 { get; set; }
        public string 开票类别 { get; set; }
        public Nullable<decimal> 税率 { get; set; }
        public string 建档日期 { get; set; }
        public string 建档人编码 { get; set; }
        public string 客户英文名称 { get; set; }
        public Nullable<int> 使用状态 { get; set; }
        public string 国家 { get; set; }
        public string 省份 { get; set; }
        public string 城市 { get; set; }
        public string 邮编 { get; set; }
        public string 负责人 { get; set; }
        public string 网址 { get; set; }
        public string emial { get; set; }
        public string 开户银行 { get; set; }
        public string 银行帐号 { get; set; }
        public string 税号 { get; set; }
        public string 地址 { get; set; }
        public string 备注 { get; set; }
        public Nullable<int> 帐期 { get; set; }
        public Nullable<int> 本厂标志 { get; set; }
        public Nullable<int> 来料标志 { get; set; }
        public Nullable<int> 金额标志 { get; set; }
        public Nullable<int> 抵账标志 { get; set; }
        public string 别名 { get; set; }
        public Nullable<int> 信用额度 { get; set; }
        public string 计价体系 { get; set; }
        public string QQ号码 { get; set; }
        public string 微博号码 { get; set; }
        public string 财务电话 { get; set; }
        public string 财务负责人 { get; set; }
        public string 仓库电话 { get; set; }
        public string 仓库负责人 { get; set; }
        public string 货运电话 { get; set; }
        public string 货运联系人 { get; set; }
        public Nullable<int> 网络注册号 { get; set; }
        public string 城区 { get; set; }
        public string 微信号码 { get; set; }
        public Nullable<decimal> 计价系数 { get; set; }
        public string 仓库地址 { get; set; }
    }
}
