//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_订单_预收款凭单
    {
        public string 单号 { get; set; }
        public string 订单号 { get; set; }
        public string 订单名称 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public Nullable<int> 成品数量 { get; set; }
        public string 计量单位 { get; set; }
        public string 成品尺寸 { get; set; }
        public Nullable<decimal> 预收金额 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public string 送货联系方式 { get; set; }
        public string 结款方式 { get; set; }
        public string 提货方式 { get; set; }
        public Nullable<decimal> 应收金额 { get; set; }
        public string 提货说明 { get; set; }
        public string 制单人编码 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 制单日期 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public string 结算人编码 { get; set; }
        public Nullable<System.DateTime> 结算日期 { get; set; }
    }
}
