//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_报价单_Detail
    {
        public int 行号 { get; set; }
        public string 订单号 { get; set; }
        public string 印品部件 { get; set; }
        public string 纸张客户编码 { get; set; }
        public string 纸张编码 { get; set; }
        public string 纸张名称 { get; set; }
        public string 上版方式 { get; set; }
        public string 项目编码 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<int> 正面色数 { get; set; }
        public Nullable<int> 背面色数 { get; set; }
        public Nullable<int> 专色色数 { get; set; }
        public Nullable<int> 上机开数 { get; set; }
        public Nullable<decimal> 页数 { get; set; }
        public string 开料尺寸 { get; set; }
        public string 材料编码 { get; set; }
        public Nullable<decimal> 版数 { get; set; }
        public Nullable<decimal> 每帖数 { get; set; }
        public Nullable<decimal> 贴数 { get; set; }
        public Nullable<decimal> 正用数量 { get; set; }
        public Nullable<decimal> 印刷加放 { get; set; }
        public Nullable<decimal> 后道加放 { get; set; }
        public Nullable<decimal> 用纸合计 { get; set; }
        public Nullable<decimal> 合计张 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 变更单号 { get; set; }
        public Nullable<int> 不印刷 { get; set; }
        public string 色数 { get; set; }
        public Nullable<int> 长 { get; set; }
        public Nullable<int> 宽 { get; set; }
        public Nullable<decimal> 拼数 { get; set; }
    }
}
