//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_合同_Detail_工艺
    {
        public string 合同号 { get; set; }
        public string 工艺要求 { get; set; }
        public string 备注 { get; set; }
    
        public virtual T_OMS_合同_Master T_OMS_合同_Master { get; set; }
    }
}
