//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_客户日志记录表
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> 订单日期 { get; set; }
        public Nullable<System.DateTime> 制单日期 { get; set; }
        public string 制单人编码 { get; set; }
        public string 手工单号 { get; set; }
        public string 业务员编码 { get; set; }
        public string 客户编码 { get; set; }
        public Nullable<int> 装车标识 { get; set; }
        public string 订单说明 { get; set; }
        public string 发货说明 { get; set; }
        public string 结余说明 { get; set; }
        public string 办款说明 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public Nullable<int> 确认标识 { get; set; }
        public string 确认人编码 { get; set; }
        public Nullable<System.DateTime> 确认日期 { get; set; }
        public string 确认说明 { get; set; }
        public string 单据类型 { get; set; }
    }
}
