//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_工艺类别系数表
    {
        public int ID { get; set; }
        public string 工艺类别 { get; set; }
        public string 系数编码 { get; set; }
        public decimal 难度系数 { get; set; }
        public string 难度说明 { get; set; }
    }
}
