//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_订单_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_OMS_订单_Master()
        {
            this.T_OMS_订单_Detail = new HashSet<T_OMS_订单_Detail>();
        }
    
        public string 订单号 { get; set; }
        public string 报价单号 { get; set; }
        public string 产品编码 { get; set; }
        public string 订单名称 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public string 合同编号 { get; set; }
        public string 客户类型 { get; set; }
        public string 选题编号 { get; set; }
        public string 客户单号 { get; set; }
        public string 联系方式 { get; set; }
        public string 送样数量 { get; set; }
        public string 送样日期 { get; set; }
        public Nullable<int> 成品数量 { get; set; }
        public string 计量单位 { get; set; }
        public string 成品尺寸 { get; set; }
        public Nullable<int> 插页数 { get; set; }
        public Nullable<int> 页数 { get; set; }
        public Nullable<int> 开数编码 { get; set; }
        public string 装订方法 { get; set; }
        public Nullable<decimal> 预付金额 { get; set; }
        public Nullable<decimal> 返款金额 { get; set; }
        public Nullable<decimal> 纸张费 { get; set; }
        public Nullable<decimal> 制模费 { get; set; }
        public Nullable<decimal> 排刀费 { get; set; }
        public Nullable<decimal> 材料费 { get; set; }
        public Nullable<decimal> 菲林费 { get; set; }
        public Nullable<decimal> 设计费 { get; set; }
        public Nullable<decimal> 印制费 { get; set; }
        public Nullable<decimal> 手工费 { get; set; }
        public Nullable<decimal> 外协费 { get; set; }
        public Nullable<decimal> 包装费 { get; set; }
        public Nullable<decimal> 物流费 { get; set; }
        public Nullable<decimal> 油墨费 { get; set; }
        public Nullable<decimal> 调节项 { get; set; }
        public Nullable<decimal> 提成比例 { get; set; }
        public Nullable<decimal> 白画布 { get; set; }
        public Nullable<decimal> 加工费 { get; set; }
        public Nullable<decimal> 其他金额 { get; set; }
        public Nullable<decimal> 开票金额 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 单据类型 { get; set; }
        public Nullable<int> 帐期 { get; set; }
        public string 结算方式 { get; set; }
        public string 印品类别编码 { get; set; }
        public string 包装材料 { get; set; }
        public string 打包数量 { get; set; }
        public string 装箱数量 { get; set; }
        public Nullable<int> 包装数量 { get; set; }
        public string 客户地址 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public string 菲林状况 { get; set; }
        public string 样稿类型 { get; set; }
        public string 样稿随货带走 { get; set; }
        public string 加工要求 { get; set; }
        public string 制单人编码 { get; set; }
        public Nullable<System.DateTime> 核算日期 { get; set; }
        public System.DateTime 制单日期 { get; set; }
        public string 计价审核人编码 { get; set; }
        public Nullable<System.DateTime> 计价审核日期 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public Nullable<int> 送货打单标识 { get; set; }
        public Nullable<int> 报账标识 { get; set; }
        public Nullable<int> 开票标识 { get; set; }
        public Nullable<System.DateTime> 完工日期 { get; set; }
        public Nullable<int> 完工标识 { get; set; }
        public Nullable<int> 送样标识 { get; set; }
        public Nullable<int> 结账标识 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public string 标贴资料 { get; set; }
        public string 收货单位 { get; set; }
        public string 送货联系方式 { get; set; }
        public string 计价复核人编码 { get; set; }
        public Nullable<System.DateTime> 计价复核日期 { get; set; }
        public string 天头 { get; set; }
        public string 地脚 { get; set; }
        public string 订口 { get; set; }
        public string 切口 { get; set; }
        public string 书号 { get; set; }
        public Nullable<decimal> 印张 { get; set; }
        public string 定价 { get; set; }
        public string 版次 { get; set; }
        public string 装订审核人编码 { get; set; }
        public Nullable<System.DateTime> 装订审核日期 { get; set; }
        public Nullable<decimal> 已开票金额 { get; set; }
        public Nullable<decimal> 税率 { get; set; }
        public Nullable<decimal> 回款金额 { get; set; }
        public Nullable<System.DateTime> 生产审核日期 { get; set; }
        public string 墨色号 { get; set; }
        public string 印品密级 { get; set; }
        public string 印品类别 { get; set; }
        public Nullable<int> 是否开票 { get; set; }
        public string 产品级别 { get; set; }
        public string 制版要求 { get; set; }
        public string 印刷要求 { get; set; }
        public Nullable<int> 留版标识 { get; set; }
        public string 客户盯色 { get; set; }
        public string 专色色别 { get; set; }
        public Nullable<decimal> CTP版费 { get; set; }
        public Nullable<decimal> PS版费 { get; set; }
        public Nullable<decimal> 纸杯 { get; set; }
        public Nullable<decimal> 覆膜费 { get; set; }
        public Nullable<decimal> 淋膜费 { get; set; }
        public Nullable<decimal> 税费 { get; set; }
        public string 变更说明 { get; set; }
        public Nullable<decimal> 成本金额 { get; set; }
        public Nullable<decimal> 纸箱 { get; set; }
        public string 提货方式 { get; set; }
        public string 拼版出血 { get; set; }
        public Nullable<decimal> 利润系数 { get; set; }
        public Nullable<decimal> 订单利润 { get; set; }
        public Nullable<int> 出货完成 { get; set; }
        public string 出货说明 { get; set; }
        public string 总P数 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OMS_订单_Detail> T_OMS_订单_Detail { get; set; }
    }
}
