//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_出版_项目编码表
    {
        public string 项目编码 { get; set; }
        public string 项目名称 { get; set; }
        public string 工艺类别 { get; set; }
        public string 计量单位 { get; set; }
        public string 报价项目编码 { get; set; }
        public string 备注 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public Nullable<int> 排序码 { get; set; }
    }
}
