//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_开数编码表
    {
        public int 开数编码 { get; set; }
        public string 开数名称 { get; set; }
        public Nullable<int> 所属开式 { get; set; }
        public string 备注 { get; set; }
        public string 开料尺寸 { get; set; }
        public string 项目编码 { get; set; }
    }
}
