//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_工艺项目编码表
    {
        public string 项目编码 { get; set; }
        public string 项目名称 { get; set; }
        public string 工艺类别 { get; set; }
        public string 上级编码 { get; set; }
        public string 统计编码 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<int> 排序码 { get; set; }
        public Nullable<int> 报价标识 { get; set; }
        public Nullable<int> 工艺标识 { get; set; }
        public Nullable<decimal> 换单金额 { get; set; }
        public Nullable<decimal> 内部单价 { get; set; }
        public string 部门编码 { get; set; }
        public string 班组编码 { get; set; }
        public string 计数标识 { get; set; }
        public Nullable<decimal> 小时产能 { get; set; }
        public string 机台编码 { get; set; }
        public string 相关工艺 { get; set; }
        public Nullable<decimal> 计件工价 { get; set; }
        public Nullable<int> 统计标识 { get; set; }
        public Nullable<decimal> 销售单价 { get; set; }
        public string 备注 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public Nullable<int> 开数编码 { get; set; }
        public Nullable<decimal> 换贴金额 { get; set; }
        public Nullable<int> 工艺排序码 { get; set; }
    }
}
