//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OMS_订单_Detail_计价
    {
        public int ID { get; set; }
        public Nullable<int> 订单工艺号 { get; set; }
        public Nullable<int> 订单材料号 { get; set; }
        public Nullable<int> 订单Detail号 { get; set; }
        public string 订单号 { get; set; }
        public string 印品部件 { get; set; }
        public string 工艺类别 { get; set; }
        public string 项目编码 { get; set; }
        public string 计量单位 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
        public Nullable<decimal> 色数 { get; set; }
        public Nullable<decimal> 贴数 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 系数 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public Nullable<decimal> 标准单价 { get; set; }
        public Nullable<decimal> 标准金额 { get; set; }
        public string 客户编码 { get; set; }
        public string 机台编码 { get; set; }
        public string 备注 { get; set; }
        public string 部门编码 { get; set; }
        public string 统计编码 { get; set; }
        public string 变更单号 { get; set; }
        public int Flag { get; set; }
    
        public virtual T_OMS_订单_Detail T_OMS_订单_Detail { get; set; }
        public virtual T_OMS_订单_Detail_材料 T_OMS_订单_Detail_材料 { get; set; }
        public virtual T_OMS_订单_Detail_工艺 T_OMS_订单_Detail_工艺 { get; set; }
    }
}
