//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PDMS_物流申请单_Detail
    {
        public int 行号 { get; set; }
        public string 申请单号 { get; set; }
        public string 项目分类 { get; set; }
        public string 订单号 { get; set; }
        public string 订单名称 { get; set; }
        public string 客户编码 { get; set; }
        public string 业务员编码 { get; set; }
        public Nullable<decimal> 进仓费 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
    }
}
