//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PDMS_物流公司编码表
    {
        public string 物流公司编码 { get; set; }
        public string 名称 { get; set; }
        public string 简称 { get; set; }
        public string 英文名称 { get; set; }
        public Nullable<int> 使用状态 { get; set; }
        public string 类别 { get; set; }
        public Nullable<int> 抵账标志 { get; set; }
        public string 传真 { get; set; }
        public string 电话 { get; set; }
        public string 地址 { get; set; }
        public string 联系人 { get; set; }
        public string 城市 { get; set; }
        public string 国家 { get; set; }
        public string 省份 { get; set; }
        public string 邮编 { get; set; }
        public string 负责人 { get; set; }
        public string 网址 { get; set; }
        public string emial { get; set; }
        public string 开户银行 { get; set; }
        public string 银行帐号 { get; set; }
        public string 税号 { get; set; }
        public string 备注 { get; set; }
        public Nullable<int> 帐期 { get; set; }
        public Nullable<decimal> 信用额度 { get; set; }
        public Nullable<int> 常用标志 { get; set; }
        public string 应付科目 { get; set; }
        public string 预付科目 { get; set; }
    }
}
