//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PDMS_物流申请单_Master
    {
        public string 申请单号 { get; set; }
        public string 物流公司编码 { get; set; }
        public Nullable<System.DateTime> 日期 { get; set; }
        public string 摘要 { get; set; }
        public string 制单人编码 { get; set; }
        public Nullable<System.DateTime> 制单日期 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public string 目的地址2 { get; set; }
        public string 目的地址1 { get; set; }
        public string 目的地址 { get; set; }
        public string 到货地址2 { get; set; }
        public string 联系方式2 { get; set; }
        public string 到货地址1 { get; set; }
        public string 联系方式1 { get; set; }
        public string 到货地址 { get; set; }
        public string 联系方式 { get; set; }
        public string 发货人 { get; set; }
        public string 物流经办人 { get; set; }
        public string 物流方式 { get; set; }
        public Nullable<decimal> 运费金额 { get; set; }
        public Nullable<decimal> 进仓费 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 结账标志 { get; set; }
    }
}
