//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PHMS_采购申请单_Master
    {
        public string 申请单号 { get; set; }
        public string 订单号 { get; set; }
        public string 单据类型 { get; set; }
        public string 部门编码 { get; set; }
        public Nullable<System.DateTime> 日期 { get; set; }
        public string 摘要 { get; set; }
        public string 物料类别 { get; set; }
        public string 制单人编码 { get; set; }
        public string 申请人 { get; set; }
        public string 负责人 { get; set; }
        public string 审核人编码 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public string 类别 { get; set; }
        public string 会计期 { get; set; }
    }
}
