//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_单据类型编码表
    {
        public string 单据类型编码 { get; set; }
        public string 单据类型名称 { get; set; }
        public string 所属模块 { get; set; }
    }
}
