//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_岗位编码表
    {
        public string 岗位编码 { get; set; }
        public string 岗位名称 { get; set; }
        public Nullable<decimal> 岗位系数 { get; set; }
        public string 部门编码 { get; set; }
        public string 备注 { get; set; }
        public Nullable<byte> Flag { get; set; }
    }
}
