//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_组织编码表
    {
        public string 编码 { get; set; }
        public string 名称 { get; set; }
        public string 上级编码 { get; set; }
        public Nullable<int> 科室标识 { get; set; }
        public Nullable<int> 车间标识 { get; set; }
        public Nullable<int> 班组标识 { get; set; }
        public string 负责人 { get; set; }
        public string 电话 { get; set; }
        public string 车间属性 { get; set; }
        public string 备注 { get; set; }
        public Nullable<int> 质量把控 { get; set; }
    }
}
