//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_功能岗位编码表
    {
        public string 功能编码 { get; set; }
        public string 岗位编码 { get; set; }
        public string 授权人编码 { get; set; }
        public Nullable<System.DateTime> 授权日期 { get; set; }
        public string 备注 { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
