//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_人员编码表
    {
        public string 人员编码 { get; set; }
        public string 厂牌编号 { get; set; }
        public string 部门编码 { get; set; }
        public string 岗位编码 { get; set; }
        public string 姓名 { get; set; }
        public string 简称 { get; set; }
        public string 进厂日期 { get; set; }
        public string 手机 { get; set; }
        public string 性别 { get; set; }
        public string 身份证号 { get; set; }
        public string 身份证到期日期 { get; set; }
        public string 家庭住址 { get; set; }
        public string 民族 { get; set; }
        public string 学历 { get; set; }
        public string 省份 { get; set; }
        public string 在厂日期 { get; set; }
        public string 出生日期 { get; set; }
        public string 宿舍号码 { get; set; }
        public string 员工卡号 { get; set; }
        public string 员工账号 { get; set; }
        public string 班组编码 { get; set; }
        public Nullable<int> 启用标志 { get; set; }
        public Nullable<byte> 业务员标志 { get; set; }
        public Nullable<byte> 领机标志 { get; set; }
        public Nullable<byte> 调度标志 { get; set; }
        public Nullable<byte> 采购员标志 { get; set; }
        public Nullable<byte> 库管员标志 { get; set; }
        public Nullable<byte> 工艺员标志 { get; set; }
        public Nullable<byte> 质检员标志 { get; set; }
        public Nullable<byte> 统计员标志 { get; set; }
        public Nullable<byte> 核算员标志 { get; set; }
        public Nullable<byte> 核价员标志 { get; set; }
        public Nullable<byte> 设计员标志 { get; set; }
        public Nullable<byte> 组长标志 { get; set; }
        public string 备注 { get; set; }
        public string 婚姻状况 { get; set; }
        public string 籍贯 { get; set; }
        public string 政治面貌 { get; set; }
        public string 毕业学校 { get; set; }
        public string 合同编号 { get; set; }
        public string 签定日期 { get; set; }
        public string 终止日期 { get; set; }
        public string 保险种类 { get; set; }
        public string 投保日期 { get; set; }
        public Nullable<decimal> 保险基数 { get; set; }
        public string 宅电 { get; set; }
        public Nullable<int> 计薪标志 { get; set; }
        public string 离厂日期 { get; set; }
        public Nullable<int> 离职标志 { get; set; }
        public string 照片编码 { get; set; }
        public string 职务 { get; set; }
        public string 星座 { get; set; }
        public string 介绍人 { get; set; }
        public string 状态 { get; set; }
        public Nullable<int> 选择 { get; set; }
        public string 排序码 { get; set; }
        public Nullable<decimal> 日工作小时 { get; set; }
        public Nullable<int> 手工标志 { get; set; }
    }
}
