//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_功能编码表
    {
        public string 功能编码 { get; set; }
        public string 功能名称 { get; set; }
        public string 上级编码 { get; set; }
        public Nullable<int> 级别 { get; set; }
        public string 功能描述 { get; set; }
        public Nullable<int> 是否菜单 { get; set; }
        public string 排序码 { get; set; }
        public string 调用类型 { get; set; }
        public string 执行程序 { get; set; }
        public string 执行代码 { get; set; }
        public Nullable<int> 是否禁用 { get; set; }
    }
}
